namespace Clean.Architecture.Application.Products.DTOs;

/// <summary>
/// Data Transfer Objects for Product operations
/// </summary>
public record CreateProductResult(
    Guid Id,
    string Sku,
    string Name,
    string Description,
    decimal Price,
    string Category,
    string Brand,
    decimal Weight,
    string Dimensions,
    string Color,
    string Size,
    decimal? SalePrice,
    DateTime? SaleStartDate,
    DateTime? SaleEndDate,
    string MetaTitle,
    string MetaDescription,
    bool RequiresShipping,
    decimal ShippingWeight,
    bool IsFeatured,
    int SortOrder,
    List<string> Images,
    List<string> Tags,
    DateTime CreatedOnUtc);

public record ProductDto(
    Guid Id,
    string Sku,
    string Name,
    string Description,
    decimal Price,
    string Category,
    string Brand,
    decimal Weight,
    string Dimensions,
    string Color,
    string Size,
    decimal? SalePrice,
    DateTime? SaleStartDate,
    DateTime? SaleEndDate,
    string MetaTitle,
    string MetaDescription,
    bool RequiresShipping,
    decimal ShippingWeight,
    bool IsFeatured,
    int SortOrder,
    List<string> Images,
    List<string> Tags,
    decimal EffectivePrice,
    bool IsOnSale,
    bool IsActive,
    DateTime CreatedOnUtc);
