using Clean.Architecture.Domain.Products.ValueObjects;

namespace Clean.Architecture.Domain.UnitTests.Products.ValueObjects;

public class SeoMetadataTests
{
    [Fact]
    public void Create_WithValidParameters_CreatesSeoMetadata()
    {
        // Act
        var seoMetadata = SeoMetadata.Create("Test Title", "Test Description");

        // Assert
        Assert.Equal("Test Title", seoMetadata.MetaTitle);
        Assert.Equal("Test Description", seoMetadata.MetaDescription);
        Assert.True(seoMetadata.IsConfigured);
    }

    [Fact]
    public void Create_WithTitleTooLong_ThrowsArgumentException()
    {
        // Arrange
        var longTitle = new string('a', 201);

        // Act & Assert
        Assert.Throws<ArgumentException>(() => SeoMetadata.Create(longTitle, "Description"));
    }

    [Fact]
    public void Create_WithDescriptionTooLong_ThrowsArgumentException()
    {
        // Arrange
        var longDescription = new string('a', 501);

        // Act & Assert
        Assert.Throws<ArgumentException>(() => SeoMetadata.Create("Title", longDescription));
    }

    [Fact]
    public void IsConfigured_WhenTitleOrDescriptionSet_ReturnsTrue()
    {
        // Act & Assert
        Assert.True(SeoMetadata.Create("Title", null).IsConfigured);
        Assert.True(SeoMetadata.Create(null, "Description").IsConfigured);
        Assert.False(SeoMetadata.Create(null, null).IsConfigured);
    }

    [Fact]
    public void GetEffectiveMetaTitle_WithTitle_ReturnsTitle()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Custom Title", "Description");

        // Act
        var effectiveTitle = seoMetadata.GetEffectiveMetaTitle("Product Name");

        // Assert
        Assert.Equal("Custom Title", effectiveTitle);
    }

    [Fact]
    public void GetEffectiveMetaTitle_WithoutTitle_ReturnsProductName()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create(null, "Description");

        // Act
        var effectiveTitle = seoMetadata.GetEffectiveMetaTitle("Product Name");

        // Assert
        Assert.Equal("Product Name", effectiveTitle);
    }

    [Fact]
    public void GetEffectiveMetaDescription_WithDescription_ReturnsDescription()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Title", "Custom Description");

        // Act
        var effectiveDescription = seoMetadata.GetEffectiveMetaDescription("Product Description");

        // Assert
        Assert.Equal("Custom Description", effectiveDescription);
    }

    [Fact]
    public void GetEffectiveMetaDescription_WithoutDescription_ReturnsTruncatedProductDescription()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Title", null);
        var longDescription = new string('a', 200);

        // Act
        var effectiveDescription = seoMetadata.GetEffectiveMetaDescription(longDescription);

        // Assert
        Assert.Equal(160, effectiveDescription.Length);
        Assert.EndsWith("...", effectiveDescription);
    }

    [Fact]
    public void CreateAutoGenerated_WithValidParameters_CreatesAutoGeneratedMetadata()
    {
        // Act
        var seoMetadata = SeoMetadata.CreateAutoGenerated("Product Name", "Product Description", "Category", "Brand");

        // Assert
        Assert.NotNull(seoMetadata.MetaTitle);
        Assert.NotNull(seoMetadata.MetaDescription);
        Assert.Contains("Product Name", seoMetadata.MetaTitle!);
    }

    [Fact]
    public void CreateAutoGenerated_WithEmptyProductName_ThrowsArgumentException()
    {
        // Act & Assert
        Assert.Throws<ArgumentException>(() => SeoMetadata.CreateAutoGenerated("", "Description", "Category", "Brand"));
    }

    [Fact]
    public void WithMetaTitle_UpdatesMetaTitle()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Old Title", "Description");

        // Act
        var updated = seoMetadata.WithMetaTitle("New Title");

        // Assert
        Assert.Equal("New Title", updated.MetaTitle);
        Assert.Equal("Description", updated.MetaDescription);
    }

    [Fact]
    public void WithMetaDescription_UpdatesMetaDescription()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Title", "Old Description");

        // Act
        var updated = seoMetadata.WithMetaDescription("New Description");

        // Assert
        Assert.Equal("Title", updated.MetaTitle);
        Assert.Equal("New Description", updated.MetaDescription);
    }

    [Fact]
    public void GetMetaTitleStatus_ReturnsLengthAndOptimalStatus()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Short Title", "Description");

        // Act
        var (length, isOptimal) = seoMetadata.GetMetaTitleStatus();

        // Assert
        Assert.Equal(11, length);
        Assert.True(isOptimal);
    }

    [Fact]
    public void GetMetaDescriptionStatus_ReturnsLengthAndOptimalStatus()
    {
        // Arrange
        var seoMetadata = SeoMetadata.Create("Title", "Short Description");

        // Act
        var (length, isOptimal) = seoMetadata.GetMetaDescriptionStatus();

        // Assert
        Assert.Equal(17, length);
        Assert.True(isOptimal);
    }

    [Fact]
    public void Equals_WithSameValues_ReturnsTrue()
    {
        // Arrange
        var seoMetadata1 = SeoMetadata.Create("Title", "Description");
        var seoMetadata2 = SeoMetadata.Create("Title", "Description");

        // Assert
        Assert.Equal(seoMetadata1, seoMetadata2);
    }

    [Fact]
    public void Equals_WithDifferentValues_ReturnsFalse()
    {
        // Arrange
        var seoMetadata1 = SeoMetadata.Create("Title 1", "Description");
        var seoMetadata2 = SeoMetadata.Create("Title 2", "Description");

        // Assert
        Assert.NotEqual(seoMetadata1, seoMetadata2);
    }
}
